### ISSUE TITLE
TemplateSyntaxError: 'grp_tags' is not a valid tag library

### ISSUE THREAD

**Issue by lahuindai** [blitzagency/django-chatterbox#1]
Installed Django 1.8
Modules: 
amqp==1.4.6
anyjson==0.3.3
billiard==3.3.0.20
celery==3.1.18
Django==1.8.2
django-allauth==0.21.0
django-celery==3.1.16
django-chatterbox==0.0.4
django-extensions==1.5.5
django-rest-auth==0.4.0
django-rest-swagger==0.3.2
django-suit==0.2.13
djangorestframework==3.1.3
jsonfield==1.0.1
kombu==3.0.26
MySQL-python==1.2.5
oauthlib==0.7.2
pyasn1==0.1.8
python-openid==2.2.5
pytz==2015.4
PyYAML==3.11
requests==2.5.3
requests-oauthlib==0.4.2
six==1.9.0

`Internal Server Error: /admin/chatterbox/client/add/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 80, in resolve_template
    return loader.get_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/usr/local/lib/python2.7/dist-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 1163, in load
    (taglib, e))
TemplateSyntaxError: 'grp_tags' is not a valid tag library: Template library grp_tags not found, tried django.templatetags.grp_tags,suit.templatetags.grp_tags,django.contrib.admin.templatetags.grp_tags,django.contrib.staticfiles.templatetags.grp_tags,django_extensions.templatetags.grp_tags,rest_framework.templatetags.grp_tags,allauth.account.templatetags.grp_tags,allauth.socialaccount.templatetags.grp_tags`

**Comment by dinopetrone** [comment]
Terribly sorry! i have no idea why, but i never got notified of this, fixing it right now!
